<?php

/**
 * @file
 * Drupal Module: FasterWeb.
 *
 * Adds the required Javascript to all your Drupal pages to allow tracking by
 * the Google Analytics statistics package.
 *
 * @author: David Jeyachandran <https://www.drupal.org/u/david-jeyachandran>
 */

function fasterweb_page_attachments(array &$attachments) {
  if (\Drupal::currentUser()->isAnonymous()) {
    $attachments['#attached']['library'][] = 'fasterweb/fasterweb';
    // $attachments['#attached']['library'][] = 'core/drupal.autocomplete';
    // $attachments['#attached']['library'][] = 'core/jquery.form';
    // $attachments['#attached']['library'][] = 'core/drupal.ajax';
  }
}

/**
 * Implements hook_preprocess_html().
 */
function fasterweb_preprocess_html(&$variables, $hook) {
  $config = \Drupal::config('fasterweb.settings');
  
  $debug_mode = $config->get('debug_mode') == false ? false : true;
  $variables['#attached']['drupalSettings']['fasterweb']['debug'] = $debug_mode;

  $variables['#attached']['drupalSettings']['fasterweb']['urls_exclude'] = 
    _create_array($config->get('urls_exclude'), array("*logout*", "/admin_menu*", "*admin/*"));

  $variables['#attached']['drupalSettings']['fasterweb']['urls_include'] = 
    _create_array($config->get('urls_include'));
  
  $variables['#attached']['drupalSettings']['fasterweb']['urls_do_not_prefetch'] = 
    _create_array($config->get('urls_do_not_prefetch'), array("*logout*", "*/node/*/edit", "*/node/add*"));

}

function _create_array( $field_value, $default_values = []) {
  $return_array = $default_values;
  
  // convert field value into array
  foreach (explode(PHP_EOL, $field_value) as $value) {
    if (!empty($value)) {
      $return_array[] = $value;
    }
  }

  return $return_array;
}
